<h2><?php echo $site;?></h2>
<ul>
  <li><a href="dashboard.php">Home</a></li>
  <li class="has-submenu">
    <a href="#">Finance</a>
    <ul class="submenu">
      <li><a href="admin-wallet.php">Admin Wallet</a></li>
      <li><a href="#">User Wallet</a></li>
    </ul>
  </li>
  <li class="has-submenu">
    <a href="#">Transaction</a>
    <ul class="submenu">
      <li><a href="#">Deposits</a></li>
      <li><a href="#">Withdrawals</a></li>
    </ul>
  </li>
  <li><a href="#">Inventory</a></li>
  <li class="has-submenu">
    <a href="#">Users Management</a>
    <ul class="submenu">
      <li><a href="#">Users</a></li>
      <li><a href="#">Roles</a></li>
    </ul>
  </li>
  <li class="has-submenu">
    <a href="#">Report</a>
    <ul class="submenu">
      <li><a href="#">Finacial Reports</a></li>
      <li><a href="#">Performance Analytics</a></li>
    </ul>
  </li>
  <li class="has-submenu">
    <a href="#">Settings</a>
    <ul class="submenu">
      <li><a href="#">General</a></li>
      <li><a href="#">Security</a></li>
    </ul>
  </li>
  <li><a href="#" id="logout">Logout</a></li>
</ul>